version: '3'


services:
  db:
    image: mysql:latest
    env_file:
      - stores/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: game_node_sync

    expose:
      - 3306
    networks:
      - game_node_app
    restart: always
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis:
    env_file: igdb-node/.env
    image: redis:latest
    expose:
      - 6379
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

    restart: always

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

    volumes:
      - redis:/var/lib/redis

    networks:
      - game_node_app

  igdb-sync:
    build:
      context: igdb
      dockerfile: Dockerfile

    depends_on:
      - redis

    env_file: igdb/.env

    # Most of the env vars are loaded directly from .env, we only need to override some to make sure
    # the docker resources are accessible.
    environment:
      SUPERTOKENS_CORE_URI: http://supertokens:3567
      DOMAIN_API: http://app:5000
      REDIS_URL: redis://redis:6379
      SERVER_PORT: 9010

    restart: always

    command: ["cron", "-f"]

    networks:
      - game_node_app
    volumes:
      - igdb-sync:/usr/src/igdb-node-sync


networks:
  game_node_app:
    external: true

volumes:
  igdb-sync:
  redis:
  db:

