version: '3'

# The only exposed service here is the actual app.
# It's your call if you want to expose the other services to the host. However, make sure to use actual
# env variables here if you choose to map the port to the host!!


services:
  redis:
    image: redis:latest
    ports:
      - "9011:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

    restart: no

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

    volumes:
      - redis:/data

    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  redis:

